artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  db_host: "localhost"
  db_user: "root"
  db_password: "mysqlpassword"
  db_name: "emp"
  query: "SELECT * FROM honeyproduction;"
  



data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/output_data.csv
  STATUS_FILE: artifacts/data_validation/status.txt



data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/output_data.csv



model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib



model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json